#!/bin/bash
#
# Show available LaCT ASR training options
#

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
BOLD='\033[1m'
NC='\033[0m'

echo -e "${BOLD}LaCT ASR Training Options${NC}"
echo "========================="
echo ""

echo -e "${GREEN}🚀 Quick Start (Recommended)${NC}"
echo "Complete automated setup and training:"
echo ""
echo -e "${BLUE}For HPC/SLURM systems:${NC}"
echo "  sbatch ./scripts/setup_and_train.sh"
echo ""
echo -e "${BLUE}For local systems:${NC}"
echo "  ./scripts/setup_and_train_local.sh"
echo ""
echo "This will:"
echo "  • Download LibriSpeech dataset (~7GB, 100 hours)"
echo "  • Install missing dependencies"
echo "  • Start training with optimal settings"
echo "  • Automatically resume if interrupted"
echo ""

echo -e "${GREEN}📊 Dataset Size Options${NC}"
echo "Choose based on your needs and resources:"
echo ""
echo -e "${BLUE}Minimal (Testing/Development):${NC}"
echo "  # HPC: sbatch ./scripts/setup_and_train.sh --dataset-size minimal"
echo "  # Local: ./scripts/setup_and_train_local.sh --dataset-size minimal"
echo "  • Dataset: train-clean-100 + dev-clean (~100 hours)"
echo "  • Download: ~7GB"
echo "  • Training time: ~8-12 hours (GPU dependent)"
echo "  • Expected WER: ~12-15%"
echo ""
echo -e "${BLUE}Standard (Full Training):${NC}"
echo "  # HPC: sbatch ./scripts/setup_and_train.sh --dataset-size standard"
echo "  # Local: ./scripts/setup_and_train_local.sh --dataset-size standard"
echo "  • Dataset: train-clean-360 + dev-clean (~360 hours)"
echo "  • Download: ~24GB"
echo "  • Training time: ~24-48 hours"
echo "  • Expected WER: ~8-12%"
echo ""
echo -e "${BLUE}Full (Research/Best Performance):${NC}"
echo "  # HPC: sbatch ./scripts/setup_and_train.sh --dataset-size full"
echo "  # Local: ./scripts/setup_and_train_local.sh --dataset-size full"
echo "  • Dataset: All clean subsets (~500+ hours)"
echo "  • Download: ~30GB"
echo "  • Training time: ~48-72 hours"
echo "  • Expected WER: ~6-10%"
echo ""

echo -e "${GREEN}⚙️ Custom Training Parameters${NC}"
echo "Fine-tune training for your hardware:"
echo ""
echo -e "${BLUE}High-end GPU (24GB+ VRAM):${NC}"
echo "  ./scripts/setup_and_train.sh \\"
echo "    --dataset-size standard \\"
echo "    --batch-size 16 \\"
echo "    --epochs 30"
echo ""
echo -e "${BLUE}Mid-range GPU (8-16GB VRAM):${NC}"
echo "  ./scripts/setup_and_train.sh \\"
echo "    --dataset-size minimal \\"
echo "    --batch-size 8 \\"
echo "    --epochs 25"
echo ""
echo -e "${BLUE}Lower-end GPU (4-8GB VRAM):${NC}"
echo "  ./scripts/setup_and_train.sh \\"
echo "    --dataset-size minimal \\"
echo "    --batch-size 4 \\"
echo "    --epochs 20"
echo ""

echo -e "${GREEN}🔄 Resume Training${NC}"
echo "For HPC or interrupted training:"
echo ""
echo -e "${BLUE}After HPC job timeout:${NC}"
echo "  # Just run the same command again - it will auto-resume"
echo "  ./scripts/setup_and_train.sh --skip-download --data-dir /path/to/data"
echo ""
echo -e "${BLUE}Manual resume:${NC}"
echo "  ./examples/train_librispeech.sh \\"
echo "    --data-dir /path/to/LibriSpeech \\"
echo "    --output-dir ./checkpoints/existing_run"
echo ""

echo -e "${GREEN}🛠️ Manual Setup${NC}"
echo "For advanced users or custom workflows:"
echo ""
echo -e "${BLUE}1. Download dataset only:${NC}"
echo "  ./scripts/download_librispeech.sh --data-dir /custom/path"
echo ""
echo -e "${BLUE}2. Train with existing dataset:${NC}"
echo "  ./examples/train_librispeech.sh --data-dir /custom/path/LibriSpeech"
echo ""
echo -e "${BLUE}3. Custom subsets:${NC}"
echo "  ./scripts/download_librispeech.sh \\"
echo "    --subsets \"train-clean-360 train-other-500 dev-clean\""
echo ""

echo -e "${GREEN}📋 Pre-flight Checklist${NC}"
echo "Before starting training:"
echo ""
echo "✓ Check GPU memory:"
echo "  nvidia-smi"
echo ""
echo "✓ Check disk space (need ~30GB+ for full dataset):"
echo "  df -h"
echo ""
echo "✓ Verify Python environment:"
echo "  python -c \"import torch; print(torch.cuda.is_available())\""
echo ""
echo "✓ Optional - set up virtual environment:"
echo "  python -m venv lact_env"
echo "  source lact_env/bin/activate"
echo ""

echo -e "${GREEN}🎯 Monitoring Training${NC}"
echo "Track your training progress:"
echo ""
echo "• Checkpoints saved to: ./checkpoints/librispeech_base/"
echo "• Best model: ./checkpoints/librispeech_base/best_model.pt"
echo "• Training logs: Check terminal output"
echo "• Resume: Scripts automatically detect and resume from latest checkpoint"
echo ""

echo -e "${GREEN}🆘 Troubleshooting${NC}"
echo "Common issues and solutions:"
echo ""
echo -e "${YELLOW}Out of GPU memory:${NC}"
echo "  • Reduce batch size: --batch-size 4"
echo "  • Use gradient accumulation (automatic)"
echo ""
echo -e "${YELLOW}Download failures:${NC}"
echo "  • Resume: ./scripts/download_librispeech.sh --force"
echo "  • Check internet connection"
echo ""
echo -e "${YELLOW}Training crashes:${NC}"
echo "  • Check CUDA compatibility"
echo "  • Verify dataset integrity: run test script in dataset directory"
echo ""

echo -e "${GREEN}📚 More Information${NC}"
echo "• Full documentation: ./scripts/README.md"
echo "• Model details: ./README.md"
echo "• Configuration options: ./configs/"
echo ""

echo -e "${BOLD}Ready to start? Choose an option above! 🚀${NC}"
